Tag.create(name: "blaster master")
Tag.create(name: "punch-out")
Tag.create(name: "simon's quest")
Tag.create(name: "duck hunt")
Tag.create(name: "metroid")
Tag.create(name: "kid icarus")
Tag.create(name: "the legend of zelda")
Tag.create(name: "megaman 2")
Tag.create(name: "bubble bobble")
Tag.create(name: "super mario bros")

chris = User.create!(username: "Chris", password: "password", email: "lawrence.c.evans@gmail.com")
dan = User.create!(username: "Dan", password: "password", email: "djquan@gmail.com")
steve = User.create!(username: "Steve", password: "password", email: "stevenjli@gmail.com")

