Tag.create(name: "Blaster Master")
Tag.create(name: "Punch Out")
Tag.create(name: "Simon's Quest")
Tag.create(name: "Duck Hunt")
Tag.create(name: "Metroid")
Tag.create(name: "Kid Icarus")
Tag.create(name: "The Legend of Zelda")
Tag.create(name: "Megaman 2")
Tag.create(name: "Bubble Bobble")
Tag.create(name: "Super Mario Bros")

chris = User.create!(username: "Chris", password: "password")
dan = User.create!(username: "Dan", password: "password")
steve = User.create!(username: "Steve", password: "password")

